### ISSUE TITLE
Some questions

### ISSUE THREAD

**Issue by kiwi0fruit** [codelv/conda-mobile#9]
Nice project!

* Where did the need for ios/android prefixes come from? It's not nonsistent with default conda packages names now.

* How to install (for example) on Android? Now README simply suggests to install Miniconda from https://conda.io/miniconda.html But there is no Android option. The closest thing I found is Miniconda3-3.16.0-Linux-armv7l.sh from https://repo.continuum.io/miniconda/ (dated by 2015 year).

**Comment by kiwi0fruit** [comment]
P.S.

I also find Minicoda+Enaml combo the best for cross-platform desktop app development. Thanks to conda package manager and conda-forge channel it's a matter of few clicks to distribute an app like [PyAppShare](https://github.com/kiwi0fruit/pyappshare) or [(conda) constructor](https://github.com/conda/constructor) suggest.

**Comment by kiwi0fruit** [comment]
* And what about root? Is it needed? Is miniconda python interpreter installed to protected from other applications it's own directory?

* Am I right that conda utilizes hard links as it does on desktop? For example in order to have several per app environments and not eat up all the space.

* Should in this case the all miniconda apps be some kind of sub-apps all inside conda app with different registered services/apps (I don't know what it's called) buit still in the same access folder?

**Comment by frmdstryr** [comment]
Thanks for the questions.

> Where did the need for ios/android prefixes come from? It's not nonsistent with default conda packages names now.

Great question! This was a decision I made to make it more clear which version is installed and make it easier to install for all arches at once from any platform. The choice I had was either prefix package names or create separate env's for target (one for running locally, one for Android, and one for iOS) and provide api's to keep the different env's in sync. 

Basically it is to get around these issues:
1. Conda only installs packages built for your specific platform and system arch
2. Conda needs to know to install a package _for android_ vs the normal desktop package
3. Android and iOS apps require libraries for multiple arches but see item 1
4. One app can be run locally, on Android, or on iOS (when that's complete) meaning it requires libraries for each
5. Without a prefix, each library would need to support both Android and iOS and be built on MacOS because it's the only platform that supports building recipes for both targets

I can provide more info if needed, but in general adding a prefix and using a different install location was the easiest option to solve all these constraints. While it's more complicated initially (you have to add `android-<package>` vs just `<package>`) it's more clear as to what exactly is installed.

>  How to install (for example) on Android? Now README simply suggests to install Miniconda from https://conda.io/miniconda.html But there is no Android option. The closest thing I found is Miniconda3-3.16.0-Linux-armv7l.sh from https://repo.continuum.io/miniconda/ (dated by 2015 year).

Conda isn't meant to be installed on an actual device. Can you explain what you want to do?

> And what about root? Is it needed? Is miniconda python interpreter installed to protected from other applications it's own directory?

Conda should not need root. Yes, miniconda's python is separate from the system directory. It's also possible for each env to have it's own version of python as well.

> Am I right that conda utilizes hard links as it does on desktop? For example in order to have several per app environments and not eat up all the space.
> Should in this case the all miniconda apps be some kind of sub-apps all inside conda app with different registered services/apps (I don't know what it's called) buit still in the same access folder?

I suggest reading conda's docs on environments. https://conda.io/docs/user-guide/tasks/manage-environments.html. Each enaml-native app creates it's own environment and will have it's own packages that are not shared.

**Comment by kiwi0fruit** [comment]
> Conda isn't meant to be installed on an actual device

Oh, I see now how it works. I thought that conda is installed on the target device. Other questions assumed that.

Is it possible to actually port conda to Android and install it there? Conda utilizes hard links to make multiple environments need less space - reuse packages. So this functionality is very welcome on mobile devices - they don't have that much space.

**Comment by kiwi0fruit** [comment]
If package renaming was only to satisfy the constraints I heavily suggest to switch to original conda naming that utilizes architecture to separate things.

I guess adding another architecture name is possible (like android-arm or something) - if not then ask to add upstream in conda is the right way to go.

As about compiling - the best option might be to cooperate with conda-forge that has automated build system for macOS too (but I didn't get about for iOS compiling - I thought that it only possible on macOS and only if you have a developer license or something - maybe I'm wrong about it).

I'm not sure if I got the problem right but [(conda) constructor](https://github.com/conda/constructor) can create installers for different architectures from withing any other architecture. It uses precompiled conda packages and you can select the platform in the yaml spec.

I think this way of setting things up is better than app names prefixes :)

**Comment by frmdstryr** [comment]
> Is it possible to actually port conda to Android and install it there? 

I haven't tried, feel free to give it a shot.

> I guess adding another architecture name is possible (like android-arm or something) - if not then ask to add upstream in conda is the right way to go.

The conda developers also thought that might be a better way as well, there's a [discussion here](https://github.com/conda/conda-build/issues/2816) if you want to follow it.  Which route you take depends on the use case. 

If the use case is to build a pure java app, somehow bundle conda, then be able to install packages from the app, then it makes sense as you're only dealing with one arch. My use case was just building a "regular" app using python instead of java or js so I have to target building for all devices.

I could be wrong, but I don't think it will be as straightforward as they think. Just because something is built with aarch64 for MacOS or aarch64 for Linux doesn't mean it'll run on an iPhone or Android. There's subtle differences with bionic's libc and iOS's security requirements so everything needs built specifically for the target.  Many popular libraries (ex OpenSSL) have flags for android, but if they don't it can be a mess to figure out how to cross compile. If conda were to add specific arch's for each android arch and each ios arch, then it would work.

However, then you would still need to handle "building" the app for each arch. Android will require that every app include both 32 and 64-bit libraries at the end of his year. If you want to support emulators and intel tablets then you need i386 and x86_64.  So gradle needs to have libraries from 4 different android arches available to build an app that supports all devices (ignoring mips).  iOS is is better and you can probably get away with only 64-bit libraries. In all, if you want one app to support all android and iOS devices you need 6-8 different arches "somewhere" so gradle/xcode can build the app (unless there's some other way I don't know about). If you don't care about iOS or emulators it's a minimum of two.

> As about compiling - the best option might be to cooperate with conda-forge that has automated build system for macOS too (but I didn't get about for iOS compiling - I thought that it only possible on macOS and only if you have a developer license or something - maybe I'm wrong about it).

This would be nice. Travis is limited to 40 minutes so I can't really add more packages or the time runs out.

> I'm not sure if I got the problem right but (conda) constructor can create installers for different architectures from withing any other architecture. It uses precompiled conda packages and you can select the platform in the yaml spec.
> I think this way of setting things up is better than app names prefixes :)

I agree, and if there's a better way then it should be done.  I did it the easiest way I saw possible.

With that said, I've spent about two years learning the internals of python-for-android, kivy-ios, and finally building enaml-native and conda-mobile (plus months writing kivy apps before that) and have pretty well spent all of my creative energy for a while.  It was more than nights and weekends and completely unpaid, so someone else is more than welcome to take the lead as this works "good enough" for me for now.  

I'm more than happy to provide assistance if someone wants to try though. Doing it they way you mentioned is the correct way to do it.

**Comment by kiwi0fruit** [comment]
> It was more than nights and weekends and completely unpaid, so someone else is more than welcome to take the lead as this works "good enough" for me for now.

I totally understand. As I understand this still alpha and working - and even with convenience tools - proof of concept so there is still the time to fix interface issues.

**Comment by kiwi0fruit** [comment]
What I meant about adding achitecture is that it's not a matter of compiler (if it works and compiles now - it would work after changing the way we specify the same very thing actually) - it's a matter of conda API only - what architecture conda checks in the channel, what architecture conda checks the package should be, etc.

So the best from API/interface/conveniense point would be to build all that packages for arm-android, x86-android, arm-ios, etc... in advance and upload to the custom conda channel like 'conda-mobile'.

Then use a modified conda and (conda) constructor that support additional achitectures. And (conda) constructor (or a program like it) creates packed android and iOS apps by reading dependencies (with unmodified names), checks architecture in the channel and packages provided directly... and actually installs them and them they fed to android/iOS tools.

**Comment by kiwi0fruit** [comment]
So my main idea was to add missing archs to https://github.com/conda/conda/blob/4d70d98d3ffc857c72142bddbf78d34b9114b267/conda/base/constants.py#L58 and then use standard ways/tools of compiling conda packages (cross-compiling, conda-forge automated biulds), then upload them to the channel 'conda-mobile'. At this point we get reusable repo of packages. Then use that repo for creating a mobile app via something like (conda) constructor.

**Comment by frmdstryr** [comment]
Sounds good to me.

**Comment by kiwi0fruit** [comment]
Looks like fixing mentioned interface problem can only be done via patching conda in backward compatible way and proposing a PR...

**Comment by kiwi0fruit** [comment]
Looks like fixing mentioned interface problem (where to specify the arch) can only be done via patching conda in backward compatible way and proposing a PR...

Or may be a custom patch only - if it's rather simple.
